In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)
type(c)

[5 7 9]


numpy.ndarray

In [4]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [5]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [6]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive


array([1, 2, 3, 4])

In [9]:
np.arange(0, 11, 2)  # step by 2 from 0 to 11

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 2))  # an array of ones with size 2 x 2

In [13]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [14]:
np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.30123329, 0.89942814],
       [0.04419325, 0.38190735],
       [0.59398275, 0.69836066],
       [0.18823582, 0.7263467 ],
       [0.6860864 , 0.04165218]])

In [15]:
x = np.random.rand(5, 2)
x

array([[0.57365737, 0.89873022],
       [0.56982735, 0.49846413],
       [0.76191803, 0.47824262],
       [0.26750336, 0.9813744 ],
       [0.5108594 , 0.99469235]])

In [16]:
x.transpose()  # transpose of the array x

array([[0.57365737, 0.56982735, 0.76191803, 0.26750336, 0.5108594 ],
       [0.89873022, 0.49846413, 0.47824262, 0.9813744 , 0.99469235]])

In [17]:
x.mean()  # mean of all elements in the array x

0.6535269225948113

In [18]:
x.astype(int)  # convert the elements of array x to integers

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [19]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


In [22]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"Shape: {x.shape}")
    print(f"Size: {x.size}")
    print("")
    print(x)

In [23]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
Shape: (1, 2, 3, 4)
Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [24]:
y = np.ones((1, 5))
print_array(y)

Dimensions: 2
Shape: (1, 5)
Size: 5

[[1. 1. 1. 1. 1.]]


In [25]:
np.array_equal(x, y)

False

In [33]:
x=np.zeros((3))
y = x + 1
y

array([1., 1., 1.])

In [34]:
x - y

array([-1., -1., -1.])

In [35]:
x == y

array([False, False, False])

In [36]:
x * y

array([0., 0., 0.])

In [37]:
x ** y

array([0., 0., 0.])

In [38]:
x / y

array([0., 0., 0.])

In [39]:
x = np.full((4, 3), 3.14)
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [40]:
x.reshape(2, -1)  # using -1 will calculate the dimension for you (if possible)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
print_array(x.flatten())

Dimensions: 1
Shape: (12,)
Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
